fabric_version=0.161.0+26.2
minecraft_dependency=>=26.2 <26.3

excluded_mixins=AbstractContainerMenuSubclasses_scarpetMixin,AbstractContainerMenu_ctrlQCraftingMixin,AbstractCraftingMenu_scarpetMixin,AbstractFurnaceMenu_scarpetMixin,ArmorStand_scarpetMarkerMixin,Biome_scarpetMixin,BlockPredicate_scarpetMixin,DistanceManager_scarpetMixin,LevelEntityGetterAdapter_scarpetMixin,MinecraftMixin,MinecraftServer_scarpetMixin,MinecraftServer_tickspeedMixin,Minecraft_tickMixin,PersistentEntitySectionManager_scarpetMixin,ServerGamePacketListenerImplMixin,ServerLevel_scarpetMixin,TagPredicate_scarpetMixin,ThreadedLevelLightEngine_scarpetChunkCreationMixin,ThreadedLevelLightEngine_scarpetMixin,Villager_aiMixin
